---
- name: OpenVPN | AIDE | Check for DB
  stat:
    path: "{{ path_aide_db }}"
  register: aide_db_check

- name: OpenVPN | AIDE | Initialize AIDE DB
  shell: aideinit
  changed_when: false
  when: ansible_os_family == "Debian" and aide_db_check.stat.exists == false
  tags:
    - skip_ansible_lint

- name: OpenVPN | AIDE | Initialize AIDE DB
  shell: aide --init
  changed_when: false
  when: ansible_os_family == "RedHat" and aide_db_check.stat.exists == false
  tags:
    - skip_ansible_lint

- name: OpenVPN | AIDE | Copy initialized DB
  ansible.builtin.copy:
    remote_src: true
    src: /var/lib/aide/aide.db.new.gz
    dest: "{{ path_aide_db }}"
  when: ansible_os_family == "RedHat" and aide_db_check.stat.exists == false

- name: OpenVPN | AIDE | Delete old DB
  ansible.builtin.file:
    path: /var/lib/aide/aide.db.new.gz
    state: absent
  when: ansible_os_family == "RedHat" and aide_db_check.stat.exists == false

# TODO check if this file is created elsewhere (/etc/crontab, /etc/cron.daily, etc)
# Ubuntu/Debian creates a cron job in /etc/cron.daily
- name: OpenVPN | Harden Misc | Periodic run of AIDE via cron @ 04:05:00
  copy:
    content: "05 4 * * * root {{ path_bin_aide }} --check"
    dest: /etc/cron.d/aide
  when: ansible_os_family == "RedHat"

- name: OpenVPN | Harden Misc | Ensure AIDE is run via cron
  stat: path=e
  register: aide_cron
  when: ansible_os_family == "Debian"

- name: OpenVPN | Harden Misc | Check for AIDE cron job
  fail: msg="No daily cron job for running AIDE"
  when: ansible_os_family == "Debian" and aide_cron.stat.exists == false