---
- name: OpenVPN | Install | Set Distro/Version specific variables
  ansible.builtin.include_vars: "{{ item }}"
  tags:
    - 'common'
    - 'packages'
    - 'pki'
    - 'openvpn'
    - 'dns'
    - 'harden'
    - 'sysctl'
    - 'umask'
    - 'services'
    - 'kernel'
    - 'misc'
    - 'auditd'
    - 'firewall'
    - 'password'
    - 'users'
    - 'sshd'
    - 'aide'
  with_first_found:
    # - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    # - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    # - "../vars/default.yml"
  notify:
    - clear history

- ansible.builtin.include_tasks: packages.yml
  tags: ['packages']

- ansible.builtin.include_tasks: pki.yml
  tags: ['pki', 'creds']

- ansible.builtin.include_tasks: openvpn.yml
  tags: ['openvpn']

- ansible.builtin.include_tasks: dns.yml
  tags: ['dns']

- ansible.builtin.include_tasks: harden_sysctl.yml
  when: ansible_virtualization_type != "docker"
  tags: ['sysctl', 'harden']

- ansible.builtin.include_tasks: harden_umask.yml
  tags: ['umask', 'harden']

- ansible.builtin.include_tasks: harden_services.yml
  tags: ['services', 'harden']

- ansible.builtin.include_tasks: harden_kernel.yml
  when: ansible_virtualization_type != "docker"
  tags: ['kernel', 'harden']

- ansible.builtin.include_tasks: harden_misc.yml
  tags: ['misc', 'harden']

- ansible.builtin.include_tasks: harden_auditd.yml
  tags: ['auditd', 'harden']

- ansible.builtin.include_tasks: firewall.yml
  tags: ['firewall', 'harden']

- ansible.builtin.include_tasks: harden_password.yml
  tags: ['password', 'harden']

- ansible.builtin.include_tasks: harden_users.yml
  tags: ['users', 'harden']

- ansible.builtin.include_tasks: harden_sshd.yml
  tags: ['sshd', 'harden']

- ansible.builtin.include_tasks: harden_aide.yml
  tags: ['aide', 'harden']
