---
- name: OpenVPN | Audit | Set variables
  include_vars: ../../openvpn/defaults/main.yml

- name: OpenVPN | Audit | Set Distro/Version specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_version  }}.yml"
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    # - "../vars/default.yml"

- ansible.builtin.include_tasks: openscap.yml
  # For now skip debian since it's version of oscap is so old it won't support 
  # new definitions. Revisit for Debian 9
  when: ansible_distribution not in ['Debian']
- ansible.builtin.include_tasks: lynis.yml
# No package for CentOS, RHEL, etc. Maybe pull from src in the future?
- ansible.builtin.include_tasks: tiger.yml
  when: ansible_os_family == "Debian"
